// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhcgtojlmkcwqjzoyflr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoY2d0b2psbWtjd3Fqem95ZmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzgzMTgsImV4cCI6MjA3MjA1NDMxOH0.ncRXvn9yMiIhg2XTb-tD7XLU8Uus01wVa9JaBEUAkVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});